### ISSUE TITLE
Entrega del ejercicio "RNA-seq analysis of E. coli with over-expressed DNA-damage handling proteins"

### ISSUE THREAD

**Issue by martarodmo** [martarodmo/testsim#1]
Hola Tomás,
He terminado el ejercicio y me gustaría que pudieras revisarlo cuando tengas tiempo.

Saludos,
Marta Rodriguez.

**Comment by tdido** [comment]
Hola Marta.

El ejercicio está muy bien, y funciona correctamente. Tengo un comentario importante, y otro menor.

El importante primero: estás generando el index de STAR cada vez que se analiza una muestra. Esto no tiene sentido, ya que el índice es uno sólo y se puede reutilizar para todas las muestras. La idea sería moverlo al script principal, luego de descargar el genoma, para ahorrar recursos.

El comentario menor: no tiene mucho sentido repetir la generación del ambiente después de cada ejecución del pipeline, ya que como el pipeline no instala paquetes, nunca va a haber cambios en ese ambiente. Por lo tanto esa parte tiene más sentido ejecutarla a mano cuando sea necesario.

**Comment by martarodmo** [comment]
Hola Tomás,
He corregido los puntos que has mencionado y he subido una nueva versión a git.

Muchas gracias.

Saludos,
Marta

**Comment by tdido** [comment]
Perfecto, Marta. Cierro el issue para indicar que el ejercicio está completo.
